config/routes.rb
Rails.application.routes.draw do
  resources :debates
  resources :users

  resources :users do
    resources :debates
  end
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debate.rb
class Debate < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :debates
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  def index
    if params[:user_id]
      @user = current_user
      @debates = @user.debates
    else
      @debates = Debate.all
    end
  end

  def show
    @debate = Debate.find(params[:id])
  end

  def new
    @user = current_user
    @debate = @user.debates.new
  end

  def edit
  end

  def create
    @user = current_user
    @debate = @user.debates.new(debate_params)
    if @debate.save
      redirect_to debate_path(@debate) 
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private

    def debate_params
      params.require(:debate).permit(:title, :body, :category, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/debates/edit.html.erb
<h1>Debates#edit</h1>
<p>Find me in app/views/debates/edit.html.erb</p>

app/views/debates/index.html.erb
<% @debates.each do |debate|%>
  <li><%= link_to debate.title, debate_path(debate) %></li>
<% end %>

app/views/debates/new.html.erb
<h1>Create a Debate<h1>

<% @debate.errors.full_messages.each do |m| %>
  <li><%= m %></li>
<% end %>

<% if params[:user_id] %>
  <%= form_for @debate do |f| %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br><br>

    <%= f.label :category %> <br>
    <%= f.text_field :category  %> <br><br>

    <%= f.label :body %> <br>
    <%= f.text_area :body %> <br><br>
    

    <%= f.submit "Create Debate" %>

  <% end %>

<% end %>

app/views/debates/show.html.erb
<h1><%= @debate.title %></h1>

<p><%= @debate.body %><p>

app/views/home/index.html.erb
<h1>Main Page</h1>

<p><%= link_to 'Sign In', signin_path %></p>
<p><%= link_to 'Sign Up', new_user_path %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsArgue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% @user.errors.full_messages.each do |m| %>
  <li><%= m %></li>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %> <br><br>

  <%= f.label :email %>
  <%= f.text_field :email %> <br><br>

  <%= f.label :password %>
  <%= f.password_field :password %> <br><br>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %> <br><br>

  <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h1>Hello <%= @user.username %></h1>

<%= link_to 'Look at all the debates', debates_path %> <br>
<%= link_to 'Create a debate', new_user_debate_path(@user) %> <br>
<%= link_to 'Your Debates', user_debates_path(@user) %>